pipeline {
    agent any
    environment {
        ENV_DIR = 'venv'
    }
    stages {
        stage('Setup Python Environment') {
            steps {
                sh '''
                    python3 -m venv ${ENV_DIR}
                    . ${ENV_DIR}/bin/activate
                    pip install --upgrade pip
                    pip install -r flask-app/requirements.txt
                '''
            }
        }
        stage('Run Flask App') {
            steps {
                sh '''
                    . ${ENV_DIR}/bin/activate
                    nohup python flask-app/app.py > flask.log 2>&1 &
                '''
            }
        }
    }
}
